name: src
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  shared_preferences: ^2.2.0
  mysql1: ^0.20.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.2
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/Sourdough Bread.jpg
    - assets/Baguettes.jpg
    - assets/Ciabatta.jpg
    - assets/Croissants.jpg
    - assets/Muffins.jpg
    - assets/Scones.jpg
    - assets/Cookies.jpg
    - assets/Brownies & Blondies.jpg
    - assets/Cinnamon Rolls.jpg
    - assets/Specialty Cakes.jpg
    - assets/gpt-generated-branding.png
    - assets/profile_picture.png
    - assets/newlogoTransparent.png

  uses-material-design: true

  